### ISSUE TITLE
这个c++源码可以移植到安卓上吗？

### ISSUE THREAD

**Issue by WaterFloat** [scarsty/kys-cpp#20]
这个c++源码可以移植到安卓上吗？国外的好多开源pc移植游戏都有安卓版。

**Comment by scarsty** [comment]
都是标准c++，gcc可以编译，所以理论上没问题。实际上可能少数库不好处理。

**Comment by clw5180** [comment]
> 都是标准c++，gcc可以编译，所以理论上没问题。实际上可能少数库不好处理。

大佬，可以加个企鹅么，我对金庸武侠和SDL2游戏开发很感兴趣，希望能交流请教一二【抱拳】
我的企鹅⑥②③④⑨⑦②⑧①

**Comment by scarsty** [comment]
> > 都是标准c++，gcc可以编译，所以理论上没问题。实际上可能少数库不好处理。
> 
> 大佬，可以加个企鹅么，我对金庸武侠和SDL2游戏开发很感兴趣，希望能交流请教一二【抱拳】
> 我的企鹅⑥②③④⑨⑦②⑧①

请加入qq群90455474

**Comment by clw5180** [comment]
> > > 都是标准c++，gcc可以编译，所以理论上没问题。实际上可能少数库不好处理。
> > 
> > 
> > 大佬，可以加个企鹅么，我对金庸武侠和SDL2游戏开发很感兴趣，希望能交流请教一二【抱拳】
> > 我的企鹅⑥②③④⑨⑦②⑧①
> 
> 请加入qq群90455474

好的，非常感谢！
