### ISSUE TITLE
无法运行程序

### ISSUE THREAD

**Issue by lsaejn** [scarsty/kys-cpp#26]
作者，您好！
我按照说明，vcpkg下载了所有的库。
好不容易编译过去，运行时报错，应用程序无法正常启动0xc000007b,也不知道是不是动态库不对了，心塞。编译好的exe放到bin下面，跑不起来...
这是需要我把vcpkg里的dll替换掉游戏目录bin里的dll吗。

**Comment by scarsty** [comment]
可能是用了32位的dll

**Comment by lsaejn** [comment]
和编译器有关吗？我是vs2019.我尝试替换了我vcpkg的sdl2.dll到下载的游戏目录，然后游戏报错。明天再试吧。。。

**Comment by scarsty** [comment]
vcpkg安装库时要加上:x64-windows，最好把新编译出的dll都复制过去。

**Comment by linyixi** [comment]
0xc000007b 出错是pe文件有问题 , 可以对执行目录下的所有dll LoadLibrary ,通过返回值判断哪个dll有问题

**Comment by lsaejn** [comment]
忘了关闭了，谢谢各位
