### ISSUE TITLE
可以写个*nix下编译的指导吗

### ISSUE THREAD

**Issue by jerry153fish** [scarsty/kys-cpp#4]

**Comment by scarsty** [comment]
我用ubuntu编译的。
用apt安装libsdl2-dev, libsdl2_image-dev, libsdl2_ttf-dev, liblua5.3-dev, libminizip-dev。
从http://www.un4seen.com/下载bass和bassmidi的linux版，头文件和so放在编译器找得到的地方，或者手动改cmake文件。
之后用cmake应该就可以编译了。
PotDll.h如果找不到就将那一行去掉。

**Comment by tpoisonooo** [comment]
```
sudo apt-get install libsdl2-image-dev  libsdl2-ttf-dev  liblua5.3-dev libminizip-dev libsdl2-dev libminizip-dev

**Comment by tpoisonooo** [comment]
@jerry153fish   check   https://github.com/scarsty/kys-cpp/blob/master/doc/how-to-build.zh.md
